name = "Jjama3"
uuid = "1285d783-1a6d-4703-8f05-8ac83ef55592"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
